version: '3.8'

services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    container_name: ${DB_CONTAINER_NAME}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${DB_VOLUME_NAME}:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    container_name: ${WP_CONTAINER_NAME}
    volumes:
      - ${WP_VOLUME_NAME}:/var/www/html
    ports:
      - ${HTTP_PORT}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${DB_CONTAINER_NAME}
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
volumes:
    ${WP_VOLUME_NAME}:
    ${DB_VOLUME_NAME}: